import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenu } from "@/components/ui/navigation-menu";
import { NavBar } from "../../NavBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
